import type { ProjectHistory } from "@/lib/history";
import { strings } from "@/content/strings";
import { formatDate, plural, type Locale } from "@/lib/i18n";

function headline(history: ProjectHistory, locale: Locale): string | undefined {
  if (history.totalSessions === 0 || !history.firstActivityAt) return undefined;
  const t = strings[locale];
  const firstSeen = formatDate(history.firstActivityAt, locale, { month: "long", year: "numeric" });
  const sessions = plural(history.totalSessions, t.feed.session, t.feed.sessions, locale);
  const commits = history.weekly.reduce((sum, w) => sum + w.commitCount, 0);
  const commitText =
    commits > 0 ? ` · ${plural(commits, t.evolution.commit, t.evolution.commits, locale)}` : "";
  return `${t.evolution.activeSince(firstSeen)} · ${sessions}${commitText}`;
}

export function Evolution({ history, locale }: { history: ProjectHistory; locale: Locale }) {
  const t = strings[locale];
  const head = headline(history, locale);
  const hasWeekly = history.weekly.length > 0;
  const hasRecent = history.recent.length > 0;
  if (!head && !hasWeekly && !hasRecent) return null;

  return (
    <>
      {head && <p className="text-sm text-neutral-600">{head}</p>}

      <div className="mono-label mt-4">
        {t.evolution.autoGenerated}
      </div>

      {hasWeekly && (
        <ol className="mt-4 space-y-5">
          {history.weekly.map((w) => (
            <li key={w.weekOf} className="border-l-2 border-neutral-200 pl-4">
              <div className="text-xs uppercase tracking-wide text-neutral-500">
                {t.feed.weekOf(formatDate(w.weekOf, locale))}
                {w.sessionCount > 0 && (
                  <span className="ml-2 text-neutral-400">
                    · {plural(w.sessionCount, t.feed.session, t.feed.sessions, locale)}
                  </span>
                )}
              </div>
              {w.publicSummary && (
                <p lang="en" className="mt-1 italic text-neutral-500 leading-relaxed">{w.publicSummary}</p>
              )}
            </li>
          ))}
        </ol>
      )}

      {!hasWeekly && hasRecent && (
        <ol className="mt-4 space-y-4">
          {history.recent.map((s) => (
            <li key={s.sessionId} className="border-l-2 border-neutral-200 pl-4">
              <div className="text-xs uppercase tracking-wide text-neutral-500">
                {formatDate(s.startedAt, locale)}
              </div>
              <p lang="en" className="mt-1 italic text-neutral-500 leading-relaxed">{s.publicSummary}</p>
            </li>
          ))}
        </ol>
      )}
    </>
  );
}
